### PR TITLE
152 migrate to pydantic v2

### LINKED ISSUE #152: Migrate to pydantic V2
Filip has already migrated to Pydantic V2 in V0.3.0.
We need to also update entirety right now.

### PR DESCRIPTION
**Pull request by djs0109**
closes #152

### CODE REVIEW

**Comment by djs0109** [comment]
@sbanoeon could you have a look at the settings for Loki? I think it has to be restructured

**Comment by djs0109** [comment]
The JsonSchemaParser we have using now is also migrated to Pydantic V2. We need to check the implementation of the Normalized Parser, and implement a keyValue parser to enable our need. https://jugit.fz-juelich.de/iek-10/public/ict-platform/fiware-applications/jsonschemaparser/-/blob/master/examples/normalized/normalized_form.py?ref_type=heads

**Comment by sbanoeon** [comment]
@djs0109 I have adapted the changes according to new json schema parser model. Can you please have a look at it?

**Comment by djs0109** [comment]
@sbanoeon could you try to update the dependency of filip to 0.5.0?

**Comment by sbanoeon** [comment]
Just to keep a track, this is the list of forbidden characters for Fiware Orion requests https://fiware-orion.readthedocs.io/en/master/orion-api.html#general-syntax-restrictions. This is the reason we need to handle the default value for some attribute values where there are special characters which are forbidden for Fiware Orion request.

**Comment by djs0109** [comment]
Due this issue # 1626 in datamodel-code-generator, the camel case json schema cannot be parsed right now

**Comment by djs0109** [comment]
@sbanoeon now it looks good to me. I have changed the pip commands in docker file and add a hint in readme, so that the jsonschemaparser will no more in the requirments.txt. Besides, I fix some errors due to the migration. If it also looks good to you, we can merge :) thanks!

**Review by sbanoeon — APPROVED** [review]

**Pull request merged**
